### PR TITLE
Fixes for RDMA

### PR DESCRIPTION
**Pull request by mtisza**
I've spent some time debugging issues with RDMA. Without these patches RDMA did not work at all (crashes, hangs, random ping timeouts, ...). After these patches it works quite well.

This does resolve https://github.com/LINBIT/drbd/issues/58, as well as other issues.

This might seem like a duplicate of https://github.com/LINBIT/drbd/pull/65, but there was an issue I failed to detect on that one prior to submitting it (build issue due to rebasing onto latest master).

### CODE REVIEW

**Comment by wzrdtales** [comment]
@mtisza did you ever send this out by mail to them?

**Comment by mtisza** [comment]
@wzrdtales yes, but not via the mailing lists.  My changes have all been accepted, with slight modifications, and are now in the master branch.  Linbit just published a blog yesterday about the collaboration https://linbit.com/blog/how-yellowbrick-data-contributed-to-improving-linbit-open-source-software/

**Comment by wzrdtales** [comment]
ah ok, do you know if those fixes also restored compatibility to the actual OFED drivers, or just the INBOX ones?

**Comment by wzrdtales** [comment]
really glad to see someone found time to work on this, I never found time unfortunately, so thank you great work :)

**Comment by mtisza** [comment]
I do believe anything that was already working, will continue to work.  The drivers that use the hard interrupt context are what was primarily broken.  The soft interrupt ones should continue to work, and will benefit from the fixes too.  That being said I personally only tested it in one setup, which is using mlx4 driver on connectx3 NICs.

**Comment by wzrdtales** [comment]
mlx4 driver doesn't say if it is the INBOX or the OFED. They are principally named the same. Did you explicitly install the OFED driver, or did you just plug your card in and go? If the latter then it is the INBOX drivers, which are less performant and lack some features.

**Comment by mtisza** [comment]
Got it.  I installed the MLX-OFED drivers built from v4.9-6.0.6.0, since that was the most recent version at the time that still supports the older CX3 NICs.

**Comment by wzrdtales** [comment]
Ic, ok good to know. Guess I would still need to retest, since we last time tested on at least cx6. Will see when that fits into schedule

**Pull request closed without merging**
